---
controller_roles:
  - users:
      - spec_user
      - dev_user1
      - dev_user2
    role: member
    target_team: ICEOps
  - team: ICEOps
    organization: ICE
    roles:
      - execute
      - read
  - users:
      - spec_user
      - net_user1
      - net_user2
    target_team: NetOps
    role: member
  - team: NetOps
    organization: ICE
    roles:
      - execute
      - read
  - users:
      - spec_user
      - sys_user1
      - sys_user2
    target_team: SysOps
    role: member
  - team: SysOps
    organization: ICE
    roles:
      - execute
      - read
...
